export const GET_PUBLICACIONES = "GET_PUBLICACIONES";
export const GET_DETALLE_PUBLICACION = "GET_DETALLE_PUBLICACION";
export const UPDATE_PUBLI = "UPDATE_PUBLI";
export const ADD_PUBLICACION = "ADD_PUBLICACION";
export const REMOVE_PUBLICACION = "REMOVE_PUBLICACION";
export const GET_SEARCH = "GET_SEARCH";
export const INPUT_CHANGE = "INPUT_CHANGE";
